Repository handsontable/docs, pull requests merged in 2018-07, with the labels that each got.

#63 Add a missing comma in the sorting doc
  tutorials/sorting.html
Labels: CLA signed, Developed (ready for review)

#60 Update principles.html
  tutorials/principles.html
Labels: CLA signed, bug

#41 Minor rewording
  tutorials/data-binding.html
Labels: CLA signed
